// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/addon/addons.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorkspaceAddonsReader is a mock of WorkspaceAddonsReader interface.
type MockWorkspaceAddonsReader struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceAddonsReaderMockRecorder
}

// MockWorkspaceAddonsReaderMockRecorder is the mock recorder for MockWorkspaceAddonsReader.
type MockWorkspaceAddonsReaderMockRecorder struct {
	mock *MockWorkspaceAddonsReader
}

// NewMockWorkspaceAddonsReader creates a new mock instance.
func NewMockWorkspaceAddonsReader(ctrl *gomock.Controller) *MockWorkspaceAddonsReader {
	mock := &MockWorkspaceAddonsReader{ctrl: ctrl}
	mock.recorder = &MockWorkspaceAddonsReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceAddonsReader) EXPECT() *MockWorkspaceAddonsReaderMockRecorder {
	return m.recorder
}

// EnvAddonsPath mocks base method.
func (m *MockWorkspaceAddonsReader) EnvAddonsPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnvAddonsPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// EnvAddonsPath indicates an expected call of EnvAddonsPath.
func (mr *MockWorkspaceAddonsReaderMockRecorder) EnvAddonsPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnvAddonsPath", reflect.TypeOf((*MockWorkspaceAddonsReader)(nil).EnvAddonsPath))
}

// ListRegularFiles mocks base method.
func (m *MockWorkspaceAddonsReader) ListRegularFiles(dirPath string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegularFiles", dirPath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegularFiles indicates an expected call of ListRegularFiles.
func (mr *MockWorkspaceAddonsReaderMockRecorder) ListRegularFiles(dirPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegularFiles", reflect.TypeOf((*MockWorkspaceAddonsReader)(nil).ListRegularFiles), dirPath)
}

// ReadFile mocks base method.
func (m *MockWorkspaceAddonsReader) ReadFile(fPath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", fPath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockWorkspaceAddonsReaderMockRecorder) ReadFile(fPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockWorkspaceAddonsReader)(nil).ReadFile), fPath)
}

// WorkloadAddonsPath mocks base method.
func (m *MockWorkspaceAddonsReader) WorkloadAddonsPath(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkloadAddonsPath", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// WorkloadAddonsPath indicates an expected call of WorkloadAddonsPath.
func (mr *MockWorkspaceAddonsReaderMockRecorder) WorkloadAddonsPath(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkloadAddonsPath", reflect.TypeOf((*MockWorkspaceAddonsReader)(nil).WorkloadAddonsPath), name)
}
